version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run:          
     #    docker info
     #    docker build src/WebUI/ -t aspnetapp -f src/WebUI/prod.Dockerfile
         |
          mkdir .docker
          touch .docker/image.tar
     #    docker save -o .docker/image.tar aspnetapp
     - persist-to-workspace:
        root: .
        paths: .docker/image.tar
 deploy:
   machine: true
   steps:
     - attach_workspace:
        at: ./
     - run: ls -al #docker load -i .docker/image.tar
    # build image
    # - run: |         
     #    docker info
      #   docker build src/WebUI/ -t aspnetapp -f src/WebUI/prod.Dockerfile
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME
workflows:
 version: 2
 build_and_deploy:
  jobs:
   - build
      #filters:
      #  tags:
      #    only: /.*/
   #- hold:
   #   type: approval
      #filters:
      #  tags:
      #    only: /^V.*/
      #  branches:
      #    ignore: /.*/
    #  requires:
    #      - build
   - deploy:
      #filters:
      #  tags:
      #    only: /^V.*/
      #  branches:
      #    ignore: /.*/
      requires:
        - build