version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build src/WebUI/ -t aspnetapp -f src/WebUI/DockerfileProd
  
 deploy:
   machine: true
   steps:
    - run: |         
         docker info
         docker build src/WebUI/ -t aspnetapp -f src/WebUI/DockerfileProd
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME
workflows:
 version: 2
 build_and_deploy:
  jobs:
   - build
   - hold:
      type: approval
      requires:
        - build
   - deploy:
      requires:
        - hold