version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build src/WebUI/ -t aspnetapp -f src/WebUI/prod.Dockerfile
         mkdir workspace
         mkdir workspace/.docker
         docker save -o workspace/.docker/image aspnetapp
     - persist-to-workspace:
        root: workspace
        paths: .docker/
 deploy:
   machine: true
   steps:
     - attach_workspace:
        at: /workspace
     - run: docker load -i /workspace/.docker
    # build image
    # - run: |         
     #    docker info
      #   docker build src/WebUI/ -t aspnetapp -f src/WebUI/prod.Dockerfile
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME
workflows:
 version: 2
 build_and_deploy:
  jobs:
   - build:
      filters:
        tags:
          only: /.*/
   - hold:
      type: approval
      filters:
        tags:
          only: /^V.*/
        branches:
          ignore: /.*/
   - deploy:
      filters:
        tags:
          only: /^V.*/
        branches:
          ignore: /.*/
      requires:
        - hold